import type { NextPage } from 'next';
import Head from 'next/head';
import { Presentation, Projects, Skills } from '../components';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        {/* <title>Portfolio Theo - 2023</title> */}
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/profile.jpg' />
      </Head>
      <main>
        <Presentation />
        <Skills />
        <Projects />
      </main>
    </div>
  );
};

export default Home;
